### ISSUE TITLE
ALWAYS RETURN EMPTY TEXT 

### ISSUE THREAD

**Issue by hernaval** [fostermadeco/voice-search-example-app#2]
I'm very disapointed, I have setup all of stuff correctly, react native or the GCP but it always returns empty speech-to-text.
Recording is working perfectly, it shows right file information, etc.
My config : 
-expo  : 37
-React : 16.9
-expo-file-system: ~8.1.0,
 -expo-av: "~8.1.0",
OS : Android 7

Can I have workaround ?

**Comment by kellypacker** [comment]
Hello @hernaval ,

I noted in the comment by the recording options that I had that issue with Android and m4a. I could only getting it working on iOS with .wav files.
